### PR TITLE
WriteRect added

### PR DESCRIPTION
**Pull request by KurtE**
Like we have in ILI9341_t3. and ST7735_t3 and ...

Only added ability to use CENTER for X and or Y

### CODE REVIEW

**Comment by mjs513** [comment]
Still have no clue why I don't GitHub notices on PRs.  But anyway just incorporated.

**Comment by KurtE** [comment]
I am wondering if when I do a PR to you, since you are not the owner of the library you don’t get it? 

Maybe I need to explicitly put in:  <mailto:reply@reply.github.com> @mjs513

Into the text such that your ID is referenced…  

 

Wonder if SumaToy is getting all of these notifications?

**Comment by KurtE** [comment]
Again not sure if anyone wishes to play, but have an ST7789 version of the Uncanny eyes running DMA from SPI and SPI1 using frame buffers from EXTMEM using @mjs513 library... 
I am setup using two Adafruit ST7789 240x240 displays... 

-----Original Message-----
From: Frank Bösing <f.boesing@gmx.de> 
Sent: Friday, February 21, 2020 2:08 PM
To: Paul Stoffregen <paul@pjrc.com>; tim bg <mobiletb@hotmail.com>; Tom Dunigan <thdunigan@gmail.com>; 'CyberMerln .' <cybermerln@gmail.com>; Kurt Eckhardt <kurte@rockisland.com>
Subject: Re: Teensy 4.1 private beta test (minimize ITCM)

..attachment...

I need a mail-coach.

Am 21.02.2020 um 23:07 schrieb Frank Bösing:
> Attached additional linkerfiles and boards.txt for Teensy 4.0 and 4.1 
> (See Forum)
>
> These put everything but FASTRUN into the flash. If FASTRUN is not 
> used, ITCM is 0 bytes - DTCM 512KB I think this can be very useful, 
> but we should test it.
>
>
>

**Comment by KurtE** [comment]
HI Kurt
Thanks - have to go find my 7789 240x240 displays now but I am still kind
of out of it right now. :)

**Pull request merged**
